# application的配置见gitlabs
# 公共配置：http://192.168.5.252:81/zhangdb/config-repo/blob/master/sc-eureka/sc-eureka-default.yml
# dev配置：http://192.168.5.252:81/zhangdb/config-repo/blob/master/sc-eureka/sc-eureka-dev.yml